# Generated by Django 5.1.3 on 2024-12-01 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0002_breed_owner_dog_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите владельца собаки",
                null=True,
                related_name="users_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
